### ISSUE TITLE
Github Rendering of AEC_ICS_IOT_Shodan_dorks.CSV

### ISSUE THREAD

**Issue by kuehnberger** [AustrianEnergyCERT/ICS_IoT_Shodan_Dorks#1]
https://github.com/AustrianEnergyCERT/ICS_IoT_Shodan_Dorks/blob/master/AEC_ICS_IOT_Shodan_dorks.CSV

tells us:

"We can make this file beautiful and searchable if this error is corrected: Illegal quoting in line 25."

Changing 
from:
"port:18245,18246 product:""general electric"""
to:
port:18245,18246 product:'general electric'

will fix that.

**Comment by AustrianEnergyCERT** [comment]
Changing it might break the csv format, but I will have a look into that. Thanks for the feedback.

**Comment by AustrianEnergyCERT** [comment]
I checked how the shodan web interface behaves when quotes are changed. It seems like the double quotes behave like intended and single quotes do not match the exact sting. Think we will stick to the current format, as it is only the rendering issue on github.
