### ISSUE TITLE
Add automated-tank-gauges

### ISSUE THREAD

**Issue by kuehnberger** [AustrianEnergyCERT/ICS_IoT_Shodan_Dorks#2]
You might want to add:

Generic;I20100;Automated Tank-Gauge;I20100

these are Automated Tank-Gauges (Automatisierte Tankanzeige) from gas stations.

hint: most run on TCP port:10001 
hint: there are also quite a lot of already hacked ones eg. in AT: https://www.shodan.io/host/213.174.251.251

**Comment by AustrianEnergyCERT** [comment]
will have a look at it, thanks for the input

**Comment by AustrianEnergyCERT** [comment]
just added it to the dork list.
